### ISSUE TITLE
adapter about to empty

### ISSUE THREAD

**Issue by odemapp** [Arjun-sna/android-swipecards-view#1]
hey there
its a great library!!!
but i found a little bug

  @Override
            public void onAdapterAboutToEmpty(int itemsInAdapter) {
              Log.i(TAG, "Adater to be empty");
            }
this override dosnt get called

**Comment by android-rk** [comment]
also found this bug onAdapterAboutToEmpty(...) never called i think you forgot to decrease count every time adapterCount is same as in youe demo 11.

**Comment by saintjab** [comment]
Did anyone get a solution to this? I am facing same problems.

**Comment by Arjun-sna** [comment]
fixed the issue on callback onAdapterAboutToEmpty() in the latest version 1.0.2
